name: flow-paths-env
channels:
  - conda-forge
  - bioconda
  - gurobi
  - defaults
dependencies:
- python=3.10
- graph-tool
- minimap2
- gurobi=11.0
- biopython
- graphviz   
- numpy
- quast
- pip
- pip:
  - networkx
  - kneed
  - scikit-learn

